### ISSUE TITLE
Any chance of moving Nova Kirbani to the OPTIONAL_SYSTEMS download?

### ISSUE THREAD

**Issue by davidson16807** [StarCrusher96/Kerbol-StarSystem#3]
I'm trying to pick a star system for my first interstellar mission and I think an Alpha Centauri analogue is ideal. I have a 150 year save file I want to keep, but I use Outer Planets Mod and have no intention to replace its functionality, nor am I interested in stock replacement. 

I've toyed around with KSS's footprint in the GameData folder and found no technical reason this cannot be done. I can offer a pull request if need be.

Decoupling KSS functionality in general offers several advantages:

 * fewer assets on a-la-cart installs, increases performance

 * greater opportunity of attracting a wider audience

 * separation of concerns aids development

**Comment by StarCrusher96** [comment]
Next update of KSS will be completely modular.
